on: [push, pull_request]

jobs:
  test-first-run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v4
      with:
        path: build/bin
        key: aseprite-cli-${{ runner.os }}-${{ steps.prepare.outputs.sha }}
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
  test-subsequent-run:
    needs: test-first-run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - id: prepare
      run: bash ./prepare.sh
      env:
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REPOSITORY: ${{ GITHUB.REPOSITORY }}
        NEOMURA_SETUP_ASEPRITE_CLI_ACTION_REF: ${{ GITHUB.REF }}
    - id: cache
      uses: actions/cache@v4
      with:
        path: build/bin
        key: aseprite-cli-${{ runner.os }}-${{ steps.prepare.outputs.sha }}
    - run: bash ./build.sh
    - run: bash ./install.sh
    - uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        registry-url: 'https://registry.npmjs.org'
    - run: bash ./test.sh
